### ISSUE TITLE
Can't use `renum`

### ISSUE THREAD

**Issue by mega-micro** [devicefuture/atto#44]
Even after a hard reset, when I try to use renum, it just highlights to the left side and prints a new line. I have no idea why. It doesn't happen with "help", "share" etc. After pressing shift, alt or etc. the cursor stops highlighting. Happened randomly. Possibly related to #43.
![atto devtools 7](https://user-images.githubusercontent.com/130433335/232437052-77c7d27d-3fa6-4622-bf3b-e6221f1c13d8.png)
(Also, some commands' descriptions in the "help" menu are mixed up, but I posted so many issues that I don't wanna post another one)

**Comment by James-Livesey** [comment]
Haha no worries, the more issues the better! Do you get any errors in DevTools for this one?

**Comment by mega-micro** [comment]
Yeah, I checked it before, but:

(126)
`caught ParsingSyntaxError: Expected operator`
`at StringConcatExpression.parse (syntax.js:507:27)`
`at syntax.js:337:39`
`at Array.map (<anonymous>)`
`at Function.parse (syntax.js:337:26)`
`at syntax.js:286:44`
`at Array.forEach (<anonymous>)`
`at LeafExpression.parse (syntax.js:286:27)`
`at syntax.js:301:40`
`at Array.forEach (<anonymous>)`
`at LiteralNegationExpression.parse (syntax.js:301:23)`

...doesn't seem to do something with it. I tried to make a new tab for checking it without any unwanted errors and `renum`... Worked here for some reason. What is really weird, is that:
- If I make my link to a code, renum will work correctly;
but
- When I use a link to a **specific** code that I wrote, renum will not work.

**Comment by mega-micro** [comment]
I tried doing a hard reset, renum still doesnt work and I realized that this error message is actually probably related to that because it happened right after I tried to use renum.
![atto devtools 8](https://user-images.githubusercontent.com/130433335/232440676-f012d38f-cd91-410f-81ad-41a5761bf105.png)

**Comment by mega-micro** [comment]
I can send a link to that unfinished code if needed.

**Comment by mega-micro** [comment]
Tried deleting a single letter but renum still doesn't work. Code's contents probably have to do something with it.

**Comment by James-Livesey** [comment]
Okay, so `renum` only works when the code has valid syntax, and I've just fixed the code so that the syntax error is shown when `renum` doesn't work.

For your program, atto only allows the `[]` syntax after variable names (hence the `Expected operator` error which wants something like `+` after the `)` of `split`), so you'll need to edit your code to be like this:

```basic
99 pixels=split(img_cursor,",")
100 if mid$(pixels[y],x,x)
```

I think I can see where you're going with this program — I might consider adding some more graphics commands to atto to let you load and draw images to the screen quicker than using `for` and `plot` in atto!
