### ISSUE TITLE
mid$ doesn't work with 0,0 arguments

### ISSUE THREAD

**Issue by mega-micro** [devicefuture/atto#46]
`mid$` seems to work incorrectly.

`mid$("asd",1,1)` is "s",
`mid$("asd",0,1)` is "a",
`mid$("asd",1,2)` is "sd" and
`mid$("asd",0,0)` is "",
which seems incompatible.

**Comment by James-Livesey** [comment]
This is in fact expected behaviour! The second number that you provide is meant to be the length of the string to be returned, and not the last index of the portion you want. This is to replicate the behaviour of [`MID$` in Locomotive BASIC](https://www.cpcwiki.eu/index.php/Locomotive_BASIC#MID.24_.28.E2.80.B9string.E2.80.BA.2C.E2.80.B9start_position.E2.80.BA.5B.2C.E2.80.B9length_of_substring.E2.80.BA.5D.29) and [Commodore 64 BASIC](https://www.c64-wiki.com/wiki/MID$), as well as [JavaScript's `substring` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring). Therefore, having `0` as the last argument will return an empty string.

That being said, the second argument to `mid$` should be optional, which it isn't in atto yet. I'll create a new issue for this.

**Comment by James-Livesey** [comment]
Issue #47 opened.
